# Generated by Django 3.2.4 on 2021-06-23 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('ID', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='1.\tNúmero de identificación')),
                ('nombre', models.CharField(max_length=50, verbose_name='2.\tNombre completo')),
                ('telefono', models.CharField(max_length=12, verbose_name='3.\tTeléfono')),
                ('direccion', models.CharField(max_length=50, verbose_name='4.\tDirección')),
                ('email', models.CharField(max_length=50, verbose_name='5.\tEmail')),
                ('contrasenia', models.CharField(max_length=12, verbose_name='6.\tContraseña')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='7.\tPais')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
